
swagger: "2.0"
info:
  title: Felix Books API
  description: Demo For API Documentation
  version: 1.0.0
  contact:
    email: neeraj@felixtechlabs.com
  liscense:
    name: Apache 2.0
    url: "http://apache.org/"
  servers:
    -url: "http://localhost:5000/"
    description: Local server
    -url: "http://felix.com/"
    description: production server

schemes: [http, https]

paths:
  /books:
    get:
      summary: Returns Books
      description: Get all books with get Request
      responses:
        200:
          description: Success
          schema:
            type: array
            items:
              type: object 
              properties:
                _id: 
                  type: integer
                name: 
                  type: string
                author: 
                  type: string
                description: 
                  type: string
                price: 
                  type: integer
                available: 
                  type: boolean
                image: 
                  type: string

        404:
          description: No books Found

  /books/{bookId}/:
    get:
      summary: Return book by id
      description: return book
      parameters:
        - name: bookId
          in: path
          schema: 
            type: integer
      responses:
        200:
          description: success

